<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>MyBeef</title>

    <!-- Bootstrap -->
    <link href="/assets/css/style.css" rel="stylesheet">
    <link href="/assets/css/home.css" rel="stylesheet">
    <link rel="icon" href="/faviicon.ico" type="image/x-icon">
    <link href="/assets/css/tableEstoque.css" rel="stylesheet">
    <link href="/assets/css/search.css" rel="stylesheet">

    <!-- HTML5 shim e Respond.js para suporte no IE8 de elementos HTML5 e media queries -->
    <!-- ALERTA: Respond.js não funciona se você visualizar uma página file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <nav>
            <ul class="main">
              <li>
                <a href="/">Home</a>
                <ul class="drop menu6">
                  <li><a href="/">MyBeef</a></li>
                  <li><a href="#">Simular</a></li>
                  <li><a href="/contato">Contato</a></li>
                  <li><a href="/login">Login</a></li>
                  <li><a href="#">Glossário</a></li>
                  <li><a href="#">Sobre</a></li>
                </ul>
              </li>
              <li><a href="#">MyBeef</a>
                <ul class="drop menu6">
                  <li><a href="/login">Minha Conta</a></li>
                  <li><a href="/login">Propriedades</a></li>
                  <li><a href="/login">Produção</a></li>
                  <li><a href="/login">Estoque</a></li>
                  <li><a href="/login">Receitas</a></li>
                </ul>
              </li>
              <li><a href="#">Simular</a>
                <ul class="drop menu6">
                  <li><a href="/simulacaoSimples">Simples</a></li>
                  <li><a href="/simulacaointensificacao">Intensificação</a></li>
                </ul>
              </li>
              <li><a href="/contato">Contato</a>
                <ul class="drop menu4">
                </ul>
              </li>
              <li><a href="/login">Login</a>
                <ul class="drop menu6">
                  <li><a href="/novoaqui">Novo aqui?</a></li>
                </ul>
              </li>
              <li><a href="#">Glossário</a>
                <ul class="drop menu6">
                  <li><a href="#">Portal Indicadores</a></li>
                </ul>
              </li>
              <li><a href="#">Sobre</a>
                <ul class="drop menu6">
                  <li><a href="#">Quem somos</a></li>
                  <li><a href="#">Informações úteis</a></li>
                <ul class="">

                </ul>
              </li>
            </ul>
    </nav>
  </div>

  <!--
    <div>
      <form class="search-container"><button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></button></i>
        <input type="text" name="/" size=30 maxlength=30 placeholder="Digite uma data para pesquisa"/>
          </form>
      </div>-->

  <section>

    <!--for demo wrap-->
    <h1>Estoque</h1>

    <div class="tbl-header">

    <!--  <div style="margin-bottom: 6px" class="input-group">
                  <span class="input-group-addon"><i class="glyphicon glyphicon-search"></i></span>
                  <input type="text" name="nome" size=30 maxlength=30 placeholder="Digite uma data para pesquisa">
              </div> -->
      <table cellpadding="0" cellspacing="0" border="0">
        <thead>
          <tr>
            <th>Código</th>
            <th>Propriedade</th>
            <th>Data</th>
            <th>Quantidade Animais</th>
            <th>Peso Total</th>
          </tr>
        </thead>
      </table>
    </div>
    <div class="tbl-content">
      <table cellpadding="0" cellspacing="0" border="0">
        <tbody>
          <tr>
            <td>AAC</td>
            <td>AUSTRALIAN COMPANY </td>
            <td>$1.38</td>
            <td>+2.01</td>
            <td>-0.36%</td>
          </tr>
          <tr>
            <td>AAD</td>
            <td>AUSENCO</td>
            <td>$2.38</td>
            <td>-0.01</td>
            <td>-1.36%</td>
          </tr>
          <tr>
            <td>AAX</td>
            <td>ADELAIDE</td>
            <td>$3.22</td>
            <td>+0.01</td>
            <td>+1.36%</td>
          </tr>
          <tr>
            <td>XXD</td>
            <td>ADITYA BIRLA</td>
            <td>$1.02</td>
            <td>-1.01</td>
            <td>+2.36%</td>
          </tr>
          <tr>
            <td>AAC</td>
            <td>AUSTRALIAN COMPANY </td>
            <td>$1.38</td>
            <td>+2.01</td>
            <td>-0.36%</td>
          </tr>
          <tr>
            <td>AAD</td>
            <td>AUSENCO</td>
            <td>$2.38</td>
            <td>-0.01</td>
            <td>-1.36%</td>
          </tr>
          <tr>
            <td>AAX</td>
            <td>ADELAIDE</td>
            <td>$3.22</td>
            <td>+0.01</td>
            <td>+1.36%</td>
          </tr>
          <tr>
            <td>XXD</td>
            <td>ADITYA BIRLA</td>
            <td>$1.02</td>
            <td>-1.01</td>
            <td>+2.36%</td>
          </tr>
          <tr>
            <td>AAC</td>
            <td>AUSTRALIAN COMPANY </td>
            <td>$1.38</td>
            <td>+2.01</td>
            <td>-0.36%</td>
          </tr>
          <tr>
            <td>AAD</td>
            <td>AUSENCO</td>
            <td>$2.38</td>
            <td>-0.01</td>
            <td>-1.36%</td>
          </tr>
          <tr>
            <td>AAX</td>
            <td>ADELAIDE</td>
            <td>$3.22</td>
            <td>+0.01</td>
            <td>+1.36%</td>
          </tr>
          <tr>
            <td>XXD</td>
            <td>ADITYA BIRLA</td>
            <td>$1.02</td>
            <td>-1.01</td>
            <td>+2.36%</td>
          </tr>
          <tr>
            <td>AAC</td>
            <td>AUSTRALIAN COMPANY </td>
            <td>$1.38</td>
            <td>+2.01</td>
            <td>-0.36%</td>
          </tr>
          <tr>
            <td>AAD</td>
            <td>AUSENCO</td>
            <td>$2.38</td>
            <td>-0.01</td>
            <td>-1.36%</td>
          </tr>
          <tr>
            <td>AAX</td>
            <td>ADELAIDE</td>
            <td>$3.22</td>
            <td>+0.01</td>
            <td>+1.36%</td>
          </tr>
          <tr>
            <td>XXD</td>
            <td>ADITYA BIRLA</td>
            <td>$1.02</td>
            <td>-1.01</td>
            <td>+2.36%</td>
          </tr>
          <tr>
            <td>AAC</td>
            <td>AUSTRALIAN COMPANY </td>
            <td>$1.38</td>
            <td>+2.01</td>
            <td>-0.36%</td>
          </tr>
          <tr>
            <td>AAD</td>
            <td>AUSENCO</td>
            <td>$2.38</td>
            <td>-0.01</td>
            <td>-1.36%</td>
          </tr>
          <tr>
            <td>AAX</td>
            <td>ADELAIDE</td>
            <td>$3.22</td>
            <td>+0.01</td>
            <td>+1.36%</td>
          </tr>
          <tr>
            <td>XXD</td>
            <td>ADITYA BIRLA</td>
            <td>$1.02</td>
            <td>-1.01</td>
            <td>+2.36%</td>
          </tr>
          <tr>
            <td>AAC</td>
            <td>AUSTRALIAN COMPANY </td>
            <td>$1.38</td>
            <td>+2.01</td>
            <td>-0.36%</td>
          </tr>
          <tr>
            <td>AAD</td>
            <td>AUSENCO</td>
            <td>$2.38</td>
            <td>-0.01</td>
            <td>-1.36%</td>
          </tr>
          <tr>
            <td>AAX</td>
            <td>ADELAIDE</td>
            <td>$3.22</td>
            <td>+0.01</td>
            <td>+1.36%</td>
          </tr>
          <tr>
            <td>XXD</td>
            <td>ADITYA BIRLA</td>
            <td>$1.02</td>
            <td>-1.01</td>
            <td>+2.36%</td>
          </tr>
          <tr>
            <td>AAC</td>
            <td>AUSTRALIAN COMPANY </td>
            <td>$1.38</td>
            <td>+2.01</td>
            <td>-0.36%</td>
          </tr>
          <tr>
            <td>AAD</td>
            <td>AUSENCO</td>
            <td>$2.38</td>
            <td>-0.01</td>
            <td>-1.36%</td>
          </tr>
          <tr>
            <td>AAX</td>
            <td>ADELAIDE</td>
            <td>$3.22</td>
            <td>+0.01</td>
            <td>+1.36%</td>
          </tr>
          <tr>
            <td>XXD</td>
            <td>ADITYA BIRLA</td>
            <td>$1.02</td>
            <td>-1.01</td>
            <td>+2.36%</td>
          </tr>
          <tr>
            <td>AAC</td>
            <td>AUSTRALIAN COMPANY </td>
            <td>$1.38</td>
            <td>+2.01</td>
            <td>-0.36%</td>
          </tr>
          <tr>
            <td>AAD</td>
            <td>AUSENCO</td>
            <td>$2.38</td>
            <td>-0.01</td>
            <td>-1.36%</td>
          </tr>
          <tr>
            <td>AAX</td>
            <td>ADELAIDE</td>
            <td>$3.22</td>
            <td>+0.01</td>
            <td>+1.36%</td>
          </tr>
          <tr>
            <td>XXD</td>
            <td>ADITYA BIRLA</td>
            <td>$1.02</td>
            <td>-1.01</td>
            <td>+2.36%</td>
          </tr>
        </tbody>
      </table>
    </div>
  </section>


  <!-- follow me template -->
  <div class="made-with-love">
    <p>  MyBeef Embrapa</p>
  </div>



    <!-- jQuery (obrigatório para plugins JavaScript do Bootstrap) -->
    <script src="/assets/js/jquery.mim.js"></script>
    <script src="/assets/js/tableEstoque.js"></script>
    <script src="/assets/js/search.js"></script>

    <!-- Inclui todos os plugins compilados (abaixo), ou inclua arquivos separadados se necessário -->
    <script src="/assets/js/bootstrap.min.js"></script>
  </body>
</html>
