<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>MyBeef</title>

    <!-- Bootstrap -->
    <link href="/assets/css/style.css" rel="stylesheet">

    <link rel="icon" href="/faviicon.ico" type="image/x-icon">
    <link href="/assets/css/home.css" rel="stylesheet">
    <link href="/assets/css/simulacaoSimplesGrafico.css" rel="stylesheet">

    <!-- HTML5 shim e Respond.js para suporte no IE8 de elementos HTML5 e media queries -->
    <!-- ALERTA: Respond.js não funciona se você visualizar uma página file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <nav>
            <ul class="main">
              <li>
                <a href="/">Home</a>
                <ul class="drop menu6">
                  <li><a href="/">MyBeef</a></li>
                  <li><a href="#">Simular</a></li>
                  <li><a href="/contato">Contato</a></li>
                  <li><a href="/login">Login</a></li>
                  <li><a href="#">Glossário</a></li>
                  <li><a href="#">Sobre</a></li>
                </ul>
              </li>
              <li><a href="#">MyBeef</a>
                <ul class="drop menu6">
                  <li><a href="/login">Minha Conta</a></li>
                  <li><a href="/login">Propriedades</a></li>
                  <li><a href="/login">Produção</a></li>
                  <li><a href="/login">Estoque</a></li>
                  <li><a href="/login">Receitas</a></li>
                </ul>
              </li>
              <li><a href="#">Simular</a>
                <ul class="drop menu6">
                  <li><a href="/simulacaoSimples">Simples</a></li>
                  <li><a href="/simulacaointensificacao">Intensificação</a></li>
                </ul>
              </li>
              <li><a href="/contato">Contato</a>
                <ul class="drop menu4">
                </ul>
              </li>
              <li><a href="/login">Login</a>
                <ul class="drop menu6">
                  <li><a href="/novoaqui">Novo aqui?</a></li>
                </ul>
              </li>
              <li><a href="#">Glossário</a>
                <ul class="drop menu6">
                  <li><a href="#">Portal Indicadores</a></li>
                </ul>
              </li>
              <li><a href="#">Sobre</a>
                <ul class="drop menu6">
                  <li><a href="#">Quem somos</a></li>
                  <li><a href="#">Informações úteis</a></li>
                <ul class="">

                </ul>
              </li>
            </ul>
    </nav>

  <div id="contenitore">
  <div class="left">

<table>
  <caption>Variáveis</caption>
  <tbody>
    <tr><td>Desfrute</td><td>80.00</td><td style="background-color:#336699">&nbsp;</td></tr>
    <tr><td>Produtividade</td><td>68.80</td><td style="background-color:#003366">&nbsp;</td></tr>
    <tr><td>Área</td><td>30.30</td><td style="background-color:#ff6600">&nbsp;</td></tr>
    <tr><td>Mortalidade</td><td>50.20</td><td style="background-color:#ffcc00">&nbsp;</td></tr>
    <tr><td>Desmame</td><td>70.80</td><td style="background-color:#ffcc00">&nbsp;</td></tr>
    <tr><td>Lotação</td><td>60.56</td><td style="background-color:#ffcc00">&nbsp;</td></tr>
  </tbody>
</table>
  <div class="button" onclick="viewGraph()">Analisar</div>
</div>
<div class="left">
  <div id="grafico">
      <div class="riga" style="top:25%"><div>75%</div></div>
      <div class="riga" style="top:50%"><div>50%</div></div>
      <div class="riga" style="top:75%"><div>25%</div></div>
      <div class="riga" style="top:75%"><div>35%</div></div>
      <div class="riga" style="top:75%"><div>45%</div></div>
      <div class="riga" style="top:75%"><div>55%</div></div>
    <div id="col0" style="left:0; background-color:#336699;" class="column"></div>
    <div id="col1" style="left:25%; background-color:#003366;" class="column"></div>
    <div id="col2" style="left:50%; background-color:#ff6600;" class="column"></div>
    <div id="col3" style="left:75%; background-color:#ffcc00;" class="column"></div>
    <div id="col4" style="left:75%; background-color:#ffcc00;" class="column"></div>
    <div id="col5" style="left:75%; background-color:#ffcc00;" class="column"></div>

  </div>
</div>
<div class="canc"></div>
  <div style="margin: 20px auto; text-align:center;">MyBeef Embrapa</div>
</div>
    <script src="/assets/js/simulacaoSimplesGrafico.js"></script>
  </body>
</html>
