
  <link href="/assets/css/home.css" rel="stylesheet">
  <nav>
          <ul class="main">
            <li>
              <a href="/">Home</a>
              <ul class="drop menu6">
                <li><a href="/">MyBeef</a></li>
                <li><a href="/simulacaoSimples">Simular</a></li>
                <li><a href="/contato">Contato</a></li>
                <li><a href="/login">Login</a></li>
                <li><a href="#">Glossário</a></li>
                <li><a href="#">Sobre</a></li>
              </ul>
            </li>
            <li><a href="#">MyBeef</a>
              <ul class="drop menu6">
                <li><a href="/login">Minha Conta</a></li>
                <li><a href="/login">Propriedades</a></li>
                <li><a href="/login">Produção</a></li>
                <li><a href="/login">Estoque</a></li>
                <li><a href="/login">Receitas</a></li>
              </ul>
            </li>
            <li><a href="#">Simular</a>
              <ul class="drop menu6">
                <li><a href="/simulacaoSimples">Simples</a></li>
                <li><a href="/simulacaointensificacao">Intensificação</a></li>
              </ul>
            </li>
            <li><a href="/contato">Contato</a>
              <ul class="drop menu4">
              </ul>
            </li>
            <li><a href="/login">Login</a>
              <ul class="drop menu6">
                <li><a href="/novoaqui">Novo aqui?</a></li>
              </ul>
            </li>
            <li><a href="#">Glossário</a>
              <ul class="drop menu6">
                <li><a href="#">Portal Indicadores</a></li>
              </ul>
            </li>
            <li><a href="#">Sobre</a>
              <ul class="drop menu6">
                <li><a href="#">Quem somos</a></li>
                <li><a href="#">Informações úteis</a></li>
              <ul class="">

              </ul>
            </li>
          </ul>
  </nav>










        <!--<nav class="navbar navbar-default"> !-->

        <!--    <div class="container"> !-->
                <!-- Brand and toggle get grouped for better mobile display -->

          <!--      <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/">
                    <!--  <img src="/faviicon.ico" class="pull-left" />!-->
                <!--    MyBeef !-->
                <!--    </a>!-->






















        <!-- Collect the nav links, forms, and other content for toggling -->
      <!--    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <script src='http://code.jquery.com/jquery-2.1.3.min.js'></script>
            <ul class="nav navbar-nav">
                <li class="active"><a href="/">Home<span class="sr-only">(current)</span></a></li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">MyBeef <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                        <li><a href="/login">Minha Conta</a></li>
                        <li><a href="/login">Minhas Propriedades</a></li>
                        <li><a href="/custos">Custos de Produção</a></li>
                        <li><a href="/estoque">Variação do Estoque de Bovinos</a></li>
                        <li><a href="/receita">Receitas</a></li>
                  </ul>
                </li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Simular <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                        <li><a href="/simulacaoSimples">Simples</a></li>
                        <li><a href="/simulacaointensificacao">Intensificação</a></li>
                  </ul>
                </li>
                <li><a href="/contato">Contato</a></li>
                <li><a href="/login">Login</a></li>
                <li><a href="/posts">Glossário</a></li>
                <li><a href="/posts">Sobre</a></li>

                </ul>
        </div><!-- /.navbar-collapse -->
 <!--    </div><!-- /.container-fluid -->
<!--</nav>

--!>
