<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>MyBeef</title>

    <!-- Bootstrap -->
    <link href="/assets/css/style.css" rel="stylesheet">
    <link href="/assets/css/home.css" rel="stylesheet">

    <link rel="icon" href="/faviicon.ico" type="image/x-icon">

    <!-- HTML5 shim e Respond.js para suporte no IE8 de elementos HTML5 e media queries -->
    <!-- ALERTA: Respond.js não funciona se você visualizar uma página file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <link href="/assets/css/home.css" rel="stylesheet">
    <nav>
            <ul class="main">
              <li>
                <a href="/">Home</a>
                <ul class="drop menu6">
                  <li><a href="/">MyBeef</a></li>
                  <li><a href="#">Simular</a></li>
                  <li><a href="/contato">Contato</a></li>
                  <li><a href="/login">Login</a></li>
                  <li><a href="#">Glossário</a></li>
                  <li><a href="#">Sobre</a></li>
                </ul>
              </li>
              <li><a href="#">MyBeef</a>
                <ul class="drop menu6">
                  <li><a href="/login">Minha Conta</a></li>
                  <li><a href="/login">Propriedades</a></li>
                  <li><a href="/login">Produção</a></li>
                  <li><a href="/login">Estoque</a></li>
                  <li><a href="/login">Receitas</a></li>
                </ul>
              </li>
              <li><a href="#">Simular</a>
                <ul class="drop menu6">
                  <li><a href="/simulacaoSimples">Simples</a></li>
                  <li><a href="/simulacaointensificacao">Intensificação</a></li>
                </ul>
              </li>
              <li><a href="/contato">Contato</a>
                <ul class="drop menu4">
                </ul>
              </li>
              <li><a href="/login">Login</a>
                <ul class="drop menu6">
                  <li><a href="/novoaqui">Novo aqui?</a></li>
                </ul>
              </li>
              <li><a href="#">Glossário</a>
                <ul class="drop menu6">
                  <li><a href="#">Portal Indicadores</a></li>
                </ul>
              </li>
              <li><a href="#">Sobre</a>
                <ul class="drop menu6">
                  <li><a href="#">Quem somos</a></li>
                  <li><a href="#">Informações úteis</a></li>
                <ul class="">

                </ul>
              </li>
            </ul>
    </nav>

  <div class="container">

                  <div class="panel-heading">
                  </div>
                  <div class="panel-body" >
                      <form id="signupform" class="form-horizontal" role="form">

                          <div id="signupalert" style="display:none" class="alert alert-danger">
                              <p>Error:</p>
                              <span></span>
                          </div>
                                  <div class="form-group">
                                      <label for="name" class="col-md-3 control-label"><font color="white">Nome:</font></label>
                                          <div class="col-md-4">
                                              <input type="text" class="form-control" name="name" placeholder="Nome Completo">
                                          </div>
                                      </div>

                          <div class="form-group">
                              <label for="email" class="col-md-3 control-label"><font color="white">Email:</font></label>
                              <div class="col-md-6">
                                  <input type="text" class="form-control" name="email" placeholder="Email Address">
                              </div>
                          </div>

                          <div class="form-group">
                              <label for="firstname" class="col-md-3 control-label"><font color= "white">Username:</font></label>
                              <div class="col-md-3">
                                  <input type="text" class="form-control" name="firstname" placeholder="Crie um nome de usuário">
                              </div>
                          </div>

                          <div class="form-group">
                              <label for="password" class="col-md-3 control-label"><font color="white">Password:</font></label>
                              <div class="col-md-3">
                                  <input type="password" class="form-control" name="passwd" placeholder="Password">
                              </div>
                          </div>

                          <div class="custom-controls-stacked">
                                <label class="col-md-3 control-label"><font color="white">Perfil:</font></label>
                                <label class="custom-control custom-radio">
                                  <input id="radioStacked1" name="radio-stacked" type="radio" class="custom-control-input">
                                  <span class="custom-control-indicator"></span>
                                  <span class="custom-control-description"><font color="white">Produtor</font></span>
                                </label>

                                <label class="custom-control custom-radio">
                                  <input id="radioStacked2" name="radio-stacked" type="radio" class="custom-control-input">
                                  <span class="custom-control-indicator"></span>
                                  <span class="custom-control-description"><font color="white">Estudante</font></span>
                                </label>

                                <label class="custom-control custom-radio">
                                  <input id="radioStacked2" name="radio-stacked" type="radio" class="custom-control-input">
                                  <span class="custom-control-indicator"></span>
                                  <span class="custom-control-description"><font color="white">Outro</font></span>
                                </label>
                          </div>

                              <div class="form-group">
                                <label for="Pais:" class="col-md-3 control-label"><font color = "white">País:</font></label>
                                <div class="col-md-3">
                                <select class="form-control form-control-sm">
                                  <option>Small select</option>
                                 </select>
                               </div>
                              </div>

                              <div class="form-group">
                                <label for="Estado:" class="col-md-3 control-label"><font color ="white">Estado:</font></label>
                                <div class="col-md-3">
                                <select class="form-control form-control-sm">
                                    <option>Small select</option>
                                 </select>
                               </div>
                              </div>

                              <div class="form-group">
                                <label for="Cidade:" class="col-md-3 control-label"><font color = "white">Cidade:</font></label>
                                <div class="col-md-3">
                                <select class="form-control form-control-sm">
                                  <option>Small select</option>
                                 </select>
                               </div>
                             </div>

                              <div class="form-group">
                                  <label for="Localidade" class="col-md-3 control-label"><font color = "white">Localidade:</font></label>
                                  <div class="col-md-5">
                                      <input type="localidade" class="form-control" name=localidade placeholder="Informe a sua localidade">
                                  </div>
                              </div>


                            <div class="form-group">
                                  <label for="telefone" class="col-md-3 control-label"><font color = "white">Telefone:</font></label>
                                    <div class="col-md-4">
                                        <input type="telefone" class="form-control" name="telefone" placeholder="Telefone">
                                </div>
                            </div>


                        <!--  <div class="form-group">
                              <!-- Button -->
                          <!--    <div class="col-md-offset-3 col-md-9">
                                  <button id="btn-signup" type="button" class="btn btn-info"><i class="icon-hand-right"></i> Cadastrar
                                  <span style="margin-left:8px;"></span>
                                  </button>
                              </div>
                          </div>

                          <div style="border-top: 1px solid #999; padding-top:20px"  class="form-group">

                              <div class="col-md-offset-3 col-md-9">
                                  <button id="btn-fbsignup" type="button" class="btn btn-primary"><i class="icon-facebook"></i>   Sign Up with Facebook  </button>

                              </div>

                          </div>
                        -->
                          <div style="border-top"; class="form-group">
                                  <div class="col-md-offset-3 col-md-9">
                                      <a id="btn-login" href="#" class="btn btn-success">Cadastrar </a>
                                      <a id="btn-fblogin" href="#" class="btn btn-primary">Cadastrar com Facebook</a>

                                  </div>
                          </div>

                      </form>
                   </div>
              </div>


    <!-- jQuery (obrigatório para plugins JavaScript do Bootstrap) -->
    <script src="/assets/js/jquery.mim.js"></script>
    <!-- Inclui todos os plugins compilados (abaixo), ou inclua arquivos separadados se necessário -->
    <script src="/assets/js/bootstrap.min.js"></script>
  </body>
</html>
