<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>MyBeef</title>

    <!-- Bootstrap -->
    <link href="/assets/css/style.css" rel="stylesheet">
    <link href="/assets/css/home.css" rel="stylesheet">
    <link rel="icon" href="/faviicon.ico" type="image/x-icon">

    <!-- HTML5 shim e Respond.js para suporte no IE8 de elementos HTML5 e media queries -->
    <!-- ALERTA: Respond.js não funciona se você visualizar uma página file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <link href="/assets/css/home.css" rel="stylesheet">
    <nav>
            <ul class="main">
              <li>
                <a href="/">Home</a>
                <ul class="drop menu6">
                  <li><a href="/">MyBeef</a></li>
                  <li><a href="#">Simular</a></li>
                  <li><a href="/contato">Contato</a></li>
                  <li><a href="/login">Login</a></li>
                  <li><a href="#">Glossário</a></li>
                  <li><a href="#">Sobre</a></li>
                </ul>
              </li>
              <li><a href="#">MyBeef</a>
                <ul class="drop menu6">
                  <li><a href="/login">Minha Conta</a></li>
                  <li><a href="/login">Propriedades</a></li>
                  <li><a href="/login">Produção</a></li>
                  <li><a href="/login">Estoque</a></li>
                  <li><a href="/login">Receitas</a></li>
                </ul>
              </li>
              <li><a href="#">Simular</a>
                <ul class="drop menu6">
                  <li><a href="/simulacaoSimples">Simples</a></li>
                  <li><a href="/simulacaointensificacao">Intensificação</a></li>
                </ul>
              </li>
              <li><a href="/contato">Contato</a>
                <ul class="drop menu4">
                </ul>
              </li>
              <li><a href="/login">Login</a>
                <ul class="drop menu6">
                  <li><a href="/novoaqui">Novo aqui?</a></li>
                </ul>
              </li>
              <li><a href="#">Glossário</a>
                <ul class="drop menu6">
                  <li><a href="#">Portal Indicadores</a></li>
                </ul>
              </li>
              <li><a href="#">Sobre</a>
                <ul class="drop menu6">
                  <li><a href="#">Quem somos</a></li>
                  <li><a href="#">Informações úteis</a></li>
                <ul class="">

                </ul>
              </li>
            </ul>
    </nav>

  <form class="form-horizontal">
<fieldset>

<!-- Form Name -->
<legend><h1>Meu Rebanho</h1></legend>

    <fieldset class="active">
     <div class="container">
                <div class="form-group">
                    <label for="name" class="col-md-3 control-label">Ano:</label>
                          <div class="col-md-2">
                              <input type="text" class="form-control" name="name" placeholder="Informe um ano">
                                </div>
                        </div>

                        <div class="form-group">
                          <label for="Propriedade:" class="col-md-3 control-label">Propriedade:</label>
                          <div class="col-md-4">
                          <select class="form-control form-control-sm">
                            <option>Small select</option>
                           </select>
                         </div>
                        </div>

                        <div class="form-group">
                          <label for="Categoria Animal:" class="col-md-3 control-label">Categoria Animal:</label>
                          <div class="col-md-4">
                          <select class="form-control form-control-sm">
                            <option>Small select</option>
                           </select>
                         </div>
                        </div>

                        <div class="form-group">
                            <label for="Quantidade Estocada" class="col-md-3 control-label">Quantidade Estocada:</label>
                                  <div class="col-md-4">
                                      <input type="text" class="form-control" name="name" placeholder="Informe um numero de animais em estoque">
                                        </div>
                                </div>

                            <div class="form-group">
                                    <label for="Peso Estocado:" class="col-md-3 control-label">Peso Estocado:</label>
                                      <div class="col-md-4">
                                        <input type="text" class="form-control" name="name" placeholder="Informe a soma total do peso do seu rebanho">
                                              </div>
                                                  </div>
                                          <div class="form-group">
                                                <label for="Quantidade Vendida:" class="col-md-3 control-label">Quantidade Vendida:</label>
                                                      <div class="col-md-4">
                                                        <input type="text" class="form-control" name="name" placeholder="Informe o numero de animais já vendidos">
                                                              </div>
                                                                </div>

                                              <div class="form-group">
                                                            <label for="Peso já Vendido:" class="col-md-3 control-label">Peso já Vendido:</label>
                                                                <div class="col-md-4">
                                                                    <input type="text" class="form-control" name="name" placeholder="Informe o peso total de animais já vendidos">                                                                          </div>
                                                                      </div>

                                 <div style="border-top"; class="form-group">
                                         <div class="col-md-offset-3 col-md-9">
                                             <a id="btn-login" href="#" class="btn btn-success">Cadastrar </a>
                                             <a id="btn-login" href="#" class="btn btn-success">Gerenciar Minha Propriedade</a>
                                                </div>
                                                    </div>

                                  </form>
                               </div>
                      </fieldset>
                          </div>

    <!-- jQuery (obrigatório para plugins JavaScript do Bootstrap) -->
    <script src="/assets/js/jquery.mim.js"></script>
    <!-- Inclui todos os plugins compilados (abaixo), ou inclua arquivos separadados se necessário -->
    <script src="/assets/js/bootstrap.min.js"></script>
  </body>
</html>
